# Make RCS man pages.

#	$Id: Makefile,v 5.1 1990/09/14 22:26:30 hammer Exp $

install = install -c -m 444

all clean ::

install ::
	${install} ci.1 ${DESTDIR}/usr/man/man1
	${install} co.1 ${DESTDIR}/usr/man/man1
	${install} ident.1 ${DESTDIR}/usr/man/man1
	${install} merge.1 ${DESTDIR}/usr/man/man1
	${install} rcs.1 ${DESTDIR}/usr/man/man1
	${install} rcsdiff.1 ${DESTDIR}/usr/man/man1
	${install} rcsintro.1 ${DESTDIR}/usr/man/man1
	${install} rcsmerge.1 ${DESTDIR}/usr/man/man1
	${install} rlog.1 ${DESTDIR}/usr/man/man1
	${install} rcsfile.5 ${DESTDIR}/usr/man/man5
